[package]
name = "syncman-network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bincode = "1"
iroh = "0.34"
syncman = { path = "../core" }
tokio = "1"

[dev-dependencies]
automerge = "0.6"
